### ISSUE TITLE
Создать проект Hello Word!

### ISSUE THREAD

**Issue by DragonLP11** [ComputePractice2017/ask-server#1]

**Comment by DragonLP11** [comment]
@djbelyak Есть вопрос в стриме для проверки работает ли api.Run ты нажимал какую-то комбинацию клавиш. В общем как проверить что код правильно отрабатывает?

**Comment by djbelyak** [comment]
@DragonLP11 ctlr+alt+n и ctlr+alt+m. ели не заработает, то надо поставить расширение Code Runner
